### ISSUE TITLE
Package name `sqlite3` or `gosqlite3`? 

### ISSUE THREAD

**Issue by riobard** [kuroneko/gosqlite3#14]
To install this package I ran

```
go get github.com/kuroneko/gosqlite3
```

and the package ended up in

```
$GOPATH/src/github.com/kuroneko/gosqlite3
```

However, since the package name is `sqlite3`, I cannot just

```
import github.com/kuroneko/gosqlite3
```

and use `gosqlite3` because the package name is wrong. I have to 

```
mv $GOPATH/github.com/kuroneko/gosqlite3 $GOPATH/github.com/kuroneko/sqlite3
```

then do

```
import github.com/kuroneko/sqlite3
```

so that `sqlite3` refers to the correct package. Is there anything I missed, or is this the way it is supposed to work? Thanks!

**Comment by feyeleanor** [comment]
I'll change the package import when I have a spare few minutes (its naming predates the current Go toolset).

However I'm surprised you've had to manually move the installed directory as I've never had to do this, nor has anyone else reported this being necessary. Which version of the Go toolchain are you working with?

**Comment by riobard** [comment]
$ go version
go version weekly.2012-03-13

I thought the new Go1 insists that the package name be the same as the last component of the path. Is that the reason?

**Comment by feyeleanor** [comment]
Quite likely. I only recently added support for the new build system and clearly overlooked that detail.

**Comment by riobard** [comment]
I see. Actually I think this layout decision of Go will be a problem in practice. It will work if you rename the project to sqlite3, but I guess there will definitely be some name collisions on GitHub. What if you want to fork the real sqlite3 project on GitHub? You'll have to somehow name it differently…

**Comment by riobard** [comment]
Seems I was wrong in the beginning. Changed to a different computer and cloned the repo again. It worked fine, and I just have to remember to refer to the package as `sqlite3` instead of `gosqlite3`. Had no idea why it didn't work on the other computer. Will try again tomorrow and let you know. Anyway, thanks very much for your response!

**Comment by feyeleanor** [comment]
I'm glad it's now working for you. The package namespace change has to happen at some point, but I'm happy to have longer to procrastinate :)
