### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by viric** [kuroneko/gosqlite3#16]
Hello,

you say in the README: licence TBD. Have you decided the licence? I'll use this or not in a project based on that.

On the other hand, this has been the only gosqlite wrapper that I managed to build with gccgo (although it required some tweaking due to a bug in gccgo).

**Comment by feyeleanor** [comment]
We've not officially decided, but you're welcome to use it under a standard BSD license or the JSMin variant (i.e. with the "shall not be used for evil" clause, which though probably unenforceable suits my personal prejudices).

I should also add that development has been on hold for quite a few months as I'm working on other projects but if you have any changes that will reduce our bit-rot I'd be more than happy to include them.

**Comment by viric** [comment]
Even considering a single person, what's evil and what's not changes every now and then. So I'll take it as BSD. :)

**Comment by kuroneko** [comment]
I'm happy with the BSD license.  It's what I probably would have used anyway.

**Comment by feyeleanor** [comment]
It's certainly the least oppressive which is why I favour it :)

**Comment by stusmall** [comment]
Can we get that committed in the LICENSE file?  I'm looking at using this for a commercial application.  I'm pretty sure legal would kill me if I was the one who checked it in :)

**Comment by feyeleanor** [comment]
I'll try to make time for this today.

**Comment by feyeleanor** [comment]
BSD License formally added :)
