### ISSUE TITLE
Failed to go get github.com/kuroneko/gosqlite3

### ISSUE THREAD

**Issue by hugozhu** [kuroneko/gosqlite3#17]
[hugo@VM-40E908FD]$ go get github.com/kuroneko/gosqlite3
# github.com/kuroneko/gosqlite3

/tmp/go-build081626837/github.com/kuroneko/gosqlite3/_obj/backup.cgo2.o: In function `_cgo_c300e54ff575_Cfunc_sqlite3_backup_step':
src/github.com/kuroneko/gosqlite3/backup.go:87: undefined reference to`sqlite3_backup_step'
/tmp/go-build081626837/github.com/kuroneko/gosqlite3/_obj/backup.cgo2.o: In function `_cgo_c300e54ff575_Cfunc_sqlite3_backup_remaining':
src/github.com/kuroneko/gosqlite3/backup.go:76: undefined reference to`sqlite3_backup_remaining'
/tmp/go-build081626837/github.com/kuroneko/gosqlite3/_obj/backup.cgo2.o: In function `_cgo_c300e54ff575_Cfunc_sqlite3_backup_pagecount':
src/github.com/kuroneko/gosqlite3/backup.go:66: undefined reference to`sqlite3_backup_pagecount'
/tmp/go-build081626837/github.com/kuroneko/gosqlite3/_obj/backup.cgo2.o: In function `_cgo_c300e54ff575_Cfunc_sqlite3_backup_init':
src/github.com/kuroneko/gosqlite3/backup.go:56: undefined reference to`sqlite3_backup_init'
/tmp/go-build081626837/github.com/kuroneko/gosqlite3/_obj/backup.cgo2.o: In function `_cgo_c300e54ff575_Cfunc_sqlite3_backup_finish':
src/github.com/kuroneko/gosqlite3/backup.go:43: undefined reference to`sqlite3_backup_finish'
/tmp/go-build081626837/github.com/kuroneko/gosqlite3/_obj/database.cgo2.o: In function `_cgo_c300e54ff575_Cfunc_sqlite3_threadsafe':
src/github.com/kuroneko/gosqlite3/database.go:102: undefined reference to`sqlite3_threadsafe'
/tmp/go-build081626837/github.com/kuroneko/gosqlite3/_obj/database.cgo2.o: In function `_cgo_c300e54ff575_Cfunc_sqlite3_open_v2':
src/github.com/kuroneko/gosqlite3/database.go:93: undefined reference to`sqlite3_open_v2'
/tmp/go-build081626837/github.com/kuroneko/gosqlite3/_obj/database.cgo2.o: In function `gosqlite3_prepare_v2':
src/github.com/kuroneko/gosqlite3/database.go:6: undefined reference to`sqlite3_prepare_v2'
/tmp/go-build081626837/github.com/kuroneko/gosqlite3/_obj/sqlite3.cgo2.o: In function `_cgo_c300e54ff575_Cfunc_sqlite3_shutdown':
src/github.com/kuroneko/gosqlite3/sqlite3.go:51: undefined reference to`sqlite3_shutdown'
/tmp/go-build081626837/github.com/kuroneko/gosqlite3/_obj/sqlite3.cgo2.o: In function `_cgo_c300e54ff575_Cfunc_sqlite3_initialize':
src/github.com/kuroneko/gosqlite3/sqlite3.go:33: undefined reference to`sqlite3_initialize'
/tmp/go-build081626837/github.com/kuroneko/gosqlite3/_obj/statement.cgo2.o: In function `_cgo_c300e54ff575_Cfunc_sqlite3_sql':
src/github.com/kuroneko/gosqlite3/statement.go:83: undefined reference to`sqlite3_sql'
/tmp/go-build081626837/github.com/kuroneko/gosqlite3/_obj/statement.cgo2.o: In function `_cgo_c300e54ff575_Cfunc_sqlite3_clear_bindings':
src/github.com/kuroneko/gosqlite3/statement.go:43: undefined reference to`sqlite3_clear_bindings'
collect2: ld returned 1 exit status

anything wrong with my sqlite3 installation, I have SQLite version 3.7.13 2012-06-11 02:05:22

**Comment by feyeleanor** [comment]
I'll try to make time to investigate this fully at the weekend.

Are you building with the standard Go distro or with GCC? What's your OS? And do you know what compile-time options were used to build SQLite?

**Comment by hugozhu** [comment]
Hi,  

It turns our there is also an old version of sqlite-devel pkg installed on this server, so problems are gone after it's removed.  

Thanks!--  
Hugo Zhu
Sent with Sparrow (http://www.sparrowmailapp.com)

**Comment by feyeleanor** [comment]
Excellent news :)
