### ISSUE TITLE
install error on windows

### ISSUE THREAD

**Issue by cnbetac** [kuroneko/gosqlite3#19]
install on windows 7 use "go get github.com/kuroneko/gosqlite3"
get an error "backup.go:3:21: error: sqlite3.h: No such file or directory"

**Comment by feyeleanor** [comment]
Unfortunately I don't have access to a Windows dev platform so I can't investigate this for you. However I suspect you need to install sqlite before attempting to build the library and to place sqlite3.h from the sqlite3 sources in an appropriate location.

**Comment by achun** [comment]
set CGO_CFLAGS=-IF:/go/include
set CGO_LDFLAGS=-lsqlite3 -LF:/go/lib/

sqlite3.h  -> F:/go/include
sqlite3.dll -> F:/go/lib
