### ISSUE TITLE
Comiple error on version cloned on 05/26/2010

### ISSUE THREAD

**Issue by vendion** [kuroneko/gosqlite3#2]
I have just prefored a git clone on the repo today and went to run the makefile but got this output from cgo:

vendion ~/go/src/pkg/gosqlite3 $ make  
CGOPKGPATH= /home/vendion/bin/cgo  sqlite3.go  
sqlite3.go:74:1: expected declaration, found '{'  
sqlite3.go:75:2: expected declaration, found 'return'  
sqlite3.go:76:1: expected declaration, found '}'  
sqlite3.go:79:1: expected declaration, found '{'  
sqlite3.go:80:2: expected declaration, found 'return'  
sqlite3.go:81:1: expected declaration, found '}'  
make: **\* [_cgo_defun.c] Error 2 

It seems that on line 74 and line 79 the opening bracket is on a new line.  After correcting these two problems it builds correctly from what I can tell.

**Comment by kuroneko** [comment]
Ugh.  Looks like they've changed cgo's syntax slightly.  I'll fix this in the repo at some point - I just don't have much time to play with go at the moment.

**Comment by kuroneko** [comment]
Fixed in latest push.
