### ISSUE TITLE
trivial makefile change

### ISSUE THREAD

**Issue by soul9** [kuroneko/gosqlite3#3]
there recently was a change in the way go makefiles include, here's the diff
===snip===
diff --git a/Makefile b/Makefile
index 860d1f6..776d351 100644
--- a/Makefile
+++ b/Makefile
@@ -1,4 +1,4 @@
-include $(GOROOT)/src/Make.$(GOARCH)
+include $(GOROOT)/src/Make.inc

 TARG=sqlite3

**Comment by soul9** [comment]
sorry about that github messed up my diff, here is the paste: http://gist.github.com/619270

**Comment by kuroneko** [comment]
Fixed a while ago.
