### ISSUE TITLE
It seems like gob is now a top level package now

### ISSUE THREAD

**Issue by vendion** [kuroneko/gosqlite3#9]
When trying it install gosqlite3 via goinstall it errors out because it can't find "encoding/gob" but it seems like the gob package is now a top level package.

`goinstall: encoding/gob: go/build: package could not be found locally`

**Comment by feyeleanor** [comment]
My apologies for the breaking change. I track weekly with my dev tools as that's closer to the release 1 standard, and amongst the changes is the move of gob to encoding/gob.

If you check out the previous commit gosqlite3 should build correctly.

**Comment by vendion** [comment]
I wasn't able to get previous commits to build, I switched to go weekly anyways so this issue can be closed now.
